import * as Sentry from '@sentry/react-native';
import { appStorage } from '../storage/mmkv';
import {
  appEncryptor,
  bootedKeyringState,
  contactService,
  keyringService,
} from './keyringRuntime';
export { appEncryptor, contactService, keyringService };

import { findChainByID } from '@/utils/chain';
import { DappService } from './dappService';
import { NotificationService } from './notification';
import { PreferenceService } from './preference';
import { SecurityEngineService } from './securityEngine';
import { TransactionBroadcastWatcherService } from './transactionBroadcastWatcher';
import { TransactionHistoryService } from './transactionHistory';
import { TransactionWatcherService } from './transactionWatcher';
import { WhitelistService } from './whitelist';
import { SessionService } from './session';
import { RabbyPointsService } from './rabbyPoints';
import { SwapService } from './swap';
import { HDKeyringService } from './hdKeyringService';
export { customTestnetService } from './customTestnetService';
import { customRPCService } from './customRPCService';
export { customRPCService };
import { BridgeService } from './bridge';
import { GasAccountService } from './gasAccount';
import { BrowserHistoryService } from './browserHistoryService';
import { migrateAppStorage, migrateServices } from '@/migrations/migrations';
import { OfflineChainService } from './offlineChain';
import { BrowserService } from './browserService';
import { APP_STORE_NAMES } from '../storage/storeConstant';
import { MetamaskModeService } from './metamaskModeService';
import { SyncChainService } from './syncChainService';
import { PerpsService } from './perpsService';
import { CurrencyService } from './currencyService';
import { LendingService } from './lendingService';
import { perfEvents } from '../utils/perf';
import { AutoConnectService } from './autoConnect';
import { setTxRpcClient } from '../utils/tx';
import {
  setUserBehaviorTrackingOptOutCache,
  USER_BEHAVIOR_TRACKING_OPT_OUT_KEY,
} from '@/utils/trackingOptOut';
import { syncFirebaseAnalyticsCollectionWithOptOut } from '@/utils/analytics';
import { syncSentryUserBehaviorTrackingEnabled } from '@/core/sentry';
import { registerDeferredService } from './deferred';
import {
  PREFERENCE_DEFERRED_SERVICE,
  type PreferenceDeferredService,
} from './preferenceDeferred';

migrateAppStorage(appStorage);

function try_catch_issue_on_preference({
  pos,
}: {
  pos: 'before_preference' | 'after_preference';
}) {
  try {
    const preferenceData = appStorage.getItem(APP_STORE_NAMES.preference);
    if (!preferenceData && bootedKeyringState) {
      const msg = `[${pos}] keyringState is not empty but preference is empty`;
      if (__DEV__) console.error(msg);
      Sentry.captureException(new Error(msg));
    }
  } catch (error) {
    Sentry.captureException(
      new Error('Failed to get preference from appStorage: ' + error),
    );
  }
}

try_catch_issue_on_preference({ pos: 'before_preference' });
setTxRpcClient(payload => customRPCService.defaultEthRPC(payload));

export const dappService = new DappService({
  storageAdapter: appStorage,
});

export const browserHistoryService = new BrowserHistoryService({
  storageAdapter: appStorage,
});

export const sessionService = new SessionService({
  dappService,
});

export const preferenceService = new PreferenceService({
  storageAdapter: appStorage,
  keyringService,
  sessionService,
});

registerDeferredService<PreferenceDeferredService>(
  PREFERENCE_DEFERRED_SERVICE,
  {
    getPasswordIsAutoGenerated() {
      return !!preferenceService.store.passwordIsAutoGenerated;
    },
  },
);

preferenceService.setBeforeSetKV((k, v) => {
  if (k === USER_BEHAVIOR_TRACKING_OPT_OUT_KEY) {
    setUserBehaviorTrackingOptOutCache(v !== false);
    void syncFirebaseAnalyticsCollectionWithOptOut();
    syncSentryUserBehaviorTrackingEnabled();
  }

  perfEvents.emit('PREFERENCE_UPDATED', {
    key: k,
    value: v,
  });
});

try_catch_issue_on_preference({ pos: 'after_preference' });

export const whitelistService = new WhitelistService({
  storageAdapter: appStorage,
});

export const transactionHistoryService = new TransactionHistoryService({
  storageAdapter: appStorage,
  preferenceService,
});

export const notificationService = new NotificationService({
  preferenceService,
  transactionHistoryService,
});

export const transactionWatcherService = new TransactionWatcherService({
  storageAdapter: appStorage,
  transactionHistoryService,
});

export const transactionBroadcastWatcherService =
  new TransactionBroadcastWatcherService({
    storageAdapter: appStorage,
    transactionHistoryService,
    transactionWatcherService,
  });

export const securityEngineService = new SecurityEngineService({
  storageAdapter: appStorage,
});

export const autoConnectService = new AutoConnectService({
  dappService,
  getAccounts: () => keyringService.getAllVisibleAccountsArray(),
  getRecentTransactions: () => transactionHistoryService.store.transactions,
  getFallbackAccount: () => preferenceService.getFallbackAccount(),
});

const syncPendingTxs = () => {
  const pendings = transactionHistoryService
    .getTransactionGroups()
    .filter(item => item.isPending);

  pendings.forEach(item => {
    const chain = findChainByID(item.chainId);
    if (!chain || !item.maxGasTx.hash) {
      return;
    }
    const key = `${item.address}_${item.nonce}_${chain?.enum}`;

    if (transactionWatcherService.hasTx(key)) {
      return;
    }

    transactionWatcherService.addTx(key, {
      nonce: item.nonce + '',
      hash: item.maxGasTx.hash,
      chain: chain.enum,
    });
  });
};

export const rabbyPointsService = new RabbyPointsService({
  storageAdapter: appStorage,
});

export const swapService = new SwapService({
  storageAdapter: appStorage,
});

export const hdKeyringService = new HDKeyringService({
  storageAdapter: appStorage,
});

export const bridgeService = new BridgeService({
  storageAdapter: appStorage,
});

export const gasAccountService = new GasAccountService({
  storageAdapter: appStorage,
});

export const offlineChainService = new OfflineChainService({
  storageAdapter: appStorage,
});

export const browserService = new BrowserService({
  storageAdapter: appStorage,
});

export const metamaskModeService = new MetamaskModeService({
  storageAdapter: appStorage,
});

export const syncChainService = new SyncChainService({
  storageAdapter: appStorage,
});

export const perpsService = new PerpsService({
  storageAdapter: appStorage,
  keyringCrypto: {
    decryptWithPassword: value => keyringService.decryptWithPassword(value),
    encryptWithPassword: value => keyringService.encryptWithPassword(value),
    isUnlocked: () => keyringService.isUnlocked(),
  },
});

export const lendingService = new LendingService({
  storageAdapter: appStorage,
});

export const currencyService = new CurrencyService({
  storageAdapter: appStorage,
});

export { default as debugLogService } from './debugLogService';

let hasStartedServiceMaintenanceAfterStartup = false;

export function startServiceMaintenanceAfterStartup() {
  if (hasStartedServiceMaintenanceAfterStartup) {
    return;
  }

  hasStartedServiceMaintenanceAfterStartup = true;
  migrateServices({
    contactBook: contactService,
    dapps: dappService,
    bridge: bridgeService,
    browserHistory: browserHistoryService,
    preference: preferenceService,
    whitelist: whitelistService,
    txHistory: transactionHistoryService,
    transactions: transactionWatcherService,
    transactionBroadcastWatcher: transactionBroadcastWatcherService,
    securityEngine: securityEngineService,
    RabbyPoints: rabbyPointsService,
    swap: swapService,
    HDKeyRingLastAddAddrTime: hdKeyringService,
    gasAccount: gasAccountService,
    offlineChain: offlineChainService,
    browser: browserService,
    metamaskMode: metamaskModeService,
    syncChain: syncChainService,
    perps: perpsService,
    lending: lendingService,
    currency: currencyService,
  });

  transactionWatcherService.roll();
  syncPendingTxs();
}
